version: "3"

services:
  openeo_odc_driver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=ec2-52-24-100-183.us-west-2.compute.amazonaws.com
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - AWS_NO_SIGN_REQUEST=true
    ports:
      - 5001:5000
    volumes:
      - ~/tmp/:/tmp/
    restart: always
