version: "4"

services:
  postgres:
    image: postgis/postgis:12-3.4-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  explorer:
    build:
      context: .
      dockerfile: Dockerfile_explorer
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
    links:
      - postgres:postgres
    ports:
      - 9001:9000
    restart: always

  openeo_odc_driver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - AWS_DEFAULT_REGION=us-west-2
      - PRODUCT_CATALOG=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-products.csv
      - METADATA_CATALOG=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-metadata.yaml
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres
      - explorer:explorer
    ports:
      - 5001:5000
    volumes:
      - ~/tmp/:/tmp/
    restart: always

  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432
    links:
      - postgres:postgres
